# The joint state controller handles publishing transforms for any moving joints
type: "joint_state_controller/JointStateController"
publish_rate: 50

head_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: head_joint
    pid: {p: 1.0, i: 1.0, d: 0.0}